server:
  port: 9090
  servlet:
    context-path: /employee

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver

